### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by rlloyd2001** [markmarijnissen/famous-webpack-seed#7]
Followed the instructions but ended up with these errors. "Module not found: Error: Cannot resolve module 'famous/src...
![image](https://cloud.githubusercontent.com/assets/4015110/6542055/fde24cb0-c4a9-11e4-85e9-d8e43680ef8e.png)

**Comment by rlloyd2001** [comment]
![image](https://cloud.githubusercontent.com/assets/4015110/6542084/45037938-c4ab-11e4-813c-710754a04d0e.png)

**Comment by rlloyd2001** [comment]
Ah I think I've figured out what is going on... something with webpack pointing to a different node_modules.

**Comment by rlloyd2001** [comment]
Actually this is an issue because the boilerplate is looking for modules that don't exist in famous.
![image](https://cloud.githubusercontent.com/assets/4015110/6542104/453a1bae-c4ac-11e4-9a1d-eb4bf0796667.png)

**Comment by rlloyd2001** [comment]
Fixed with: 
![image](https://cloud.githubusercontent.com/assets/4015110/6542380/bcd37b0e-c4b3-11e4-9306-5c99e43978c7.png)

**Comment by talves** [comment]
Yeah, famo.us changed the path in the latest version back to the original. :)
Thanks for the catch @rlloyd2001
